GET http://localhost:3001/try-qs?a[name]=bill&a[age]=20

###

POST http://localhost:3001/try-post
Content-Type: application/x-www-form-urlencoded

name=david&gender=male
# 一定要空一排才寫內容

###
POST http://localhost:3001/try-post
Content-Type: application/json

{"name":"flora","gender":"female"}